controller_list:
  - name: fake_xarm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - left_finger_joint
      - right_finger_joint
initial:  # Define initial robot poses.
  - group: xarm
    pose: Home_1